# Generated by Django 3.0.8 on 2020-08-02 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descriptiion',
            new_name='descriptions',
        ),
    ]
